# Generated by Django 6.0.1 on 2026-02-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='scenario',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
