# Generated by Django 6.0.1 on 2026-02-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_alter_scenario_options_scenario_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='decision_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
