# Generated by Django 6.0.1 on 2026-02-06 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='explanation',
            field=models.TextField(default=django.utils.timezone.now, help_text='Explanation shown if the user answers incorrectly'),
            preserve_default=False,
        ),
    ]
